In [53]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tqdm import tqdm


In [54]:
# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)
n_residual_blocks = 5
# The data, split between train and test sets
(x, _), (y, _) = keras.datasets.mnist.load_data()
# Concatenate all of the images together
data = np.concatenate((x, y), axis=0)
# Round all pixel values less than 33% of the max 256 value to 0
# anything above this value gets rounded up to 1 so that all values are either
# 0 or 1
data = np.where(data < (0.33 * 256), 0, 1)
data = data.astype(np.float32)


In [55]:
data.shape

(70000, 28, 28)

In [56]:
# The first layer is the PixelCNN layer. This layer simply
# builds on the 2D convolutional layer, but includes masking.
class PixelConvLayer(layers.Layer):
    def __init__(self, mask_type, **kwargs):
        super(PixelConvLayer, self).__init__()
        self.mask_type = mask_type
        self.conv = layers.Conv2D(**kwargs)

    def build(self, input_shape):
        # Build the conv2d layer to initialize kerneconv2dl variables
        self.conv.build(input_shape)
        # Use the initialized kernel to create the mask
        kernel_shape = self.conv.kernel.get_shape()
        self.mask = np.zeros(shape=kernel_shape)
        self.mask[: kernel_shape[0] // 2, ...] = 1.0
        self.mask[kernel_shape[0] // 2, : kernel_shape[1] // 2, ...] = 1.0
        if self.mask_type == "B":
            self.mask[kernel_shape[0] // 2, kernel_shape[1] // 2, ...] = 1.0

    def call(self, inputs):
        self.conv.kernel.assign(self.conv.kernel * self.mask)
        return self.conv(inputs)


# Next, we build our residual block layer.
# This is just a normal residual block, but based on the PixelConvLayer.
class ResidualBlock(keras.layers.Layer):
    def __init__(self, filters, **kwargs):
        super(ResidualBlock, self).__init__(**kwargs)
        self.conv1 = keras.layers.Conv2D(
            filters=filters, kernel_size=1, activation="relu"
        )
        self.pixel_conv = PixelConvLayer(
            mask_type="B",
            filters=filters // 2,
            kernel_size=3,
            activation="relu",
            padding="same",
        )
        self.conv2 = keras.layers.Conv2D(
            filters=filters, kernel_size=1, activation="relu"
        )

    def call(self, inputs):
        x = self.conv1(inputs)
        x = self.pixel_conv(x)
        x = self.conv2(x)
        return keras.layers.add([inputs, x])


In [57]:
inputs = keras.Input(shape=input_shape)
x = PixelConvLayer(
    mask_type="A", filters=128, kernel_size=7, activation="relu", padding="same"
)(inputs)

for _ in range(n_residual_blocks):
    x = ResidualBlock(filters=128)(x)

for _ in range(2):
    x = PixelConvLayer(
        mask_type="B",
        filters=128,
        kernel_size=1,
        strides=1,
        activation="relu",
        padding="valid",
    )(x)

out = keras.layers.Conv2D(
    filters=1, kernel_size=1, strides=1, activation="sigmoid", padding="valid"
)(x)

pixel_cnn = keras.Model(inputs, out)
adam = keras.optimizers.Adam(learning_rate=0.0005)
pixel_cnn.compile(optimizer=adam, loss="binary_crossentropy" )

pixel_cnn.summary()
pixel_cnn.fit(
    x=data, y=data, batch_size=128, epochs=50, validation_split=0.1, verbose=2
)

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
pixel_conv_layer_32 (PixelCo (None, 28, 28, 128)       6400      
_________________________________________________________________
residual_block_20 (ResidualB (None, 28, 28, 128)       98624     
_________________________________________________________________
residual_block_21 (ResidualB (None, 28, 28, 128)       98624     
_________________________________________________________________
residual_block_22 (ResidualB (None, 28, 28, 128)       98624     
_________________________________________________________________
residual_block_23 (ResidualB (None, 28, 28, 128)       98624     
_________________________________________________________________
residual_block_24 (ResidualB (None, 28, 28, 128)       9862

In [84]:
 tf.random.uniform((4,))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.9412769 , 0.01695979, 0.82117116, 0.6151278 ], dtype=float32)>

In [86]:
tf.math.ceil([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([-1., -1., -0.,  1.,  2.,  2.,  2.], dtype=float32)>

In [85]:
from IPython.display import Image, display

# Create an empty array of pixels.
batch = 4
pixels = np.zeros(shape=(batch,) + (pixel_cnn.input_shape)[1:])
batch, rows, cols, channels = pixels.shape

# Iterate over the pixels because generation has to be done sequentially pixel by pixel.
for row in tqdm(range(rows)):
    for col in range(cols):
        for channel in range(channels):
            # Feed the whole array and retrieving the pixel value probabilities for the next
            # pixel.
            probs = pixel_cnn.predict(pixels)[:, row, col, channel]
            
            # Use the probabilities to pick pixel values and append the values to the image
            # frame.
            
            print(probs)
            #print(probs - tf.random.uniform(probs.shape))
            #print(tf.math.ceil(probs - tf.random.uniform(probs.shape , seed = 10)))
            pixels[:, row, col, channel] = tf.math.ceil(
                probs - tf.random.uniform(probs.shape)
            )


def deprocess_image(x):
    # Stack the single channeled black and white image to RGB values.
    x = np.stack((x, x, x), 2)
    # Undo preprocessing
    x *= 255.0
    # Convert to uint8 and clip to the valid range [0, 255]
    x = np.clip(x, 0, 255).astype("uint8")
    return x


# Iterate over the generated images and plot them with matplotlib.
for i, pic in enumerate(pixels):
    keras.preprocessing.image.save_img(
        "generated_image_{}.png".format(i), deprocess_image(np.squeeze(pic, -1))
    )

display(Image("generated_image_0.png"))
display(Image("generated_image_1.png"))
display(Image("generated_image_2.png"))
display(Image("generated_image_3.png"))


  0%|          | 0/28 [00:00<?, ?it/s]

[2.345803e-07 2.345803e-07 2.345803e-07 2.345803e-07]
[3.923414e-07 3.923414e-07 3.923414e-07 3.923414e-07]
[3.0153237e-07 3.0153237e-07 3.0153237e-07 3.0153237e-07]
[1.0634633e-06 1.0634633e-06 1.0634633e-06 1.0634633e-06]
[1.9531935e-06 1.9531935e-06 1.9531935e-06 1.9531935e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.2067177e-06 2.2067177e-06 2.2067177e-06]
[2.2067177e-06 2.20671

  4%|▎         | 1/28 [00:01<00:28,  1.06s/it]

[2.2067136e-06 2.2067136e-06 2.2067136e-06 2.2067136e-06]
[2.2067093e-06 2.2067093e-06 2.2067093e-06 2.2067093e-06]
[2.2067159e-06 2.2067159e-06 2.2067159e-06 2.2067159e-06]
[2.2067159e-06 2.2067159e-06 2.2067159e-06 2.2067159e-06]
[7.01618e-08 7.01618e-08 7.01618e-08 7.01618e-08]
[3.4926475e-06 3.4926475e-06 3.4926475e-06 3.4926475e-06]
[7.573923e-07 7.573923e-07 7.573923e-07 7.573923e-07]
[9.98258e-06 9.98258e-06 9.98258e-06 9.98258e-06]
[3.1216587e-05 3.1216587e-05 3.1216587e-05 3.1216587e-05]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00022052]
[0.00022052 0.00022052 0.00022052 0.00

  7%|▋         | 2/28 [00:02<00:26,  1.02s/it]

[4.903673e-06 4.903673e-06 4.903673e-06 4.903673e-06]
[3.7171578e-08 3.7171578e-08 3.7171578e-08 3.7171578e-08]
[1.6781943e-06 1.6781943e-06 1.6781943e-06 1.6781943e-06]
[4.7532476e-06 4.7532476e-06 4.7532476e-06 4.7532476e-06]
[9.190473e-06 9.190473e-06 9.190473e-06 9.190473e-06]
[4.4977118e-05 4.4977118e-05 4.4977118e-05 4.4977118e-05]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00

 11%|█         | 3/28 [00:03<00:24,  1.01it/s]

[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[0.00197633 0.00197633 0.00197633 0.00197633]
[4.548024e-05 4.548024e-05 4.548024e-05 4.548024e-05]
[4.330431e-06 4.330431e-06 4.330431e-06 4.330431e-06]
[1.2168985e-07 1.2168985e-07 1.2168985e-07 1.2168985e-07]
[3.2999678e-06 3.2999678e-06 3.2999678e-06 3.2999678e-06]
[1.2701909e-05 1.2701909e-05 1.2701909e-05 1.2701909e-05]
[9.234498e-06 9.234498e-06 9.234498e-06 9.234498e-06]
[3.4162542e-05 3.4162542e-05 3.4162542e-05 3.4162542e-05]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369627 0.00369627 0.00369627 0.00369627]
[0.00369

 14%|█▍        | 4/28 [00:03<00:23,  1.02it/s]

[1.1438063e-05 1.1438063e-05 1.1438063e-05 1.1438063e-05]
[4.435259e-06 4.435259e-06 4.435259e-06 4.435259e-06]
[9.902325e-07 9.902325e-07 9.902325e-07 9.902325e-07]
[5.5504897e-06 5.5504897e-06 5.5504897e-06 5.5504897e-06]
[1.9622448e-05 1.9622448e-05 1.9622448e-05 1.9622448e-05]
[0.00016869 0.00016869 0.00016869 0.00016869]
[0.0002544 0.0002544 0.0002544 0.0002544]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.0167424

 18%|█▊        | 5/28 [00:04<00:22,  1.03it/s]

[0.01674248 0.01674248 0.01674248 0.01674248]
[0.01674248 0.01674248 0.01674248 0.01674248]
[0.00035767 0.00035767 0.00035767 0.00035767]
[0.00015504 0.00015504 0.00015504 0.00015504]
[3.1728363e-05 3.1728363e-05 3.1728363e-05 3.1728363e-05]
[1.3738229e-05 1.3738229e-05 1.3738229e-05 1.3738229e-05]
[3.5795672e-06 3.5795672e-06 3.5795672e-06 3.5795672e-06]
[4.843669e-05 4.843669e-05 4.843669e-05 4.843669e-05]
[0.00028492 0.00028492 0.00028492 0.00028492]
[0.00059212 0.00059212 0.00059212 0.00059212]
[0.00135178 0.00135178 0.00135178 0.00135178]
[0.02057226 0.02057226 0.02057226 0.02057226]
[0.02057226 0.02057226 0.02057226 0.02057226]
[0.02057226 0.02057226 0.02057226 0.02057226]
[0.92670685 0.02057226 0.02057226 0.02057226]
[0.813448   0.02057226 0.02057226 0.02057226]
[0.8164098  0.02057226 0.02057226 0.02057226]
[0.8043677  0.02057226 0.02057226 0.02057226]
[0.7599423  0.02057226 0.02057226 0.02057226]
[0.7203466  0.92670685 0.02057226 0.02057226]
[0.01597949 0.81344813 0.92670685 0.

 21%|██▏       | 6/28 [00:06<00:23,  1.05s/it]

[0.00033534 0.00033534 0.00033534 0.00033534]
[6.756427e-05 6.756427e-05 6.756427e-05 6.756427e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[3.5795638e-06 3.5795672e-06 3.5795672e-06 3.5795672e-06]
[4.843669e-05 4.843669e-05 4.843669e-05 4.843669e-05]
[0.00028492 0.00028492 0.00028492 0.00028492]
[0.00059212 0.00059212 0.00059212 0.00059212]
[0.02020437 0.00135179 0.00135178 0.00135178]
[0.30765867 0.02057226 0.02057226 0.02057226]
[0.99899215 0.02057225 0.02057226 0.02057226]
[0.999482   0.02057225 0.02057225 0.02057226]
[0.9961796  0.02057225 0.02057225 0.02057226]
[0.99217236 0.08215268 0.02057225 0.02057226]
[0.9947791  0.30765873 0.08215268 0.02057226]
[0.9976949  0.6821971  0.30765864 0.92670685]
[0.9918499  0.9997452  0.54923356 0.81344813]
[0.7660001  0.99431914 0.97882825 0.81640977]
[0.3594109 0.9872574 0.9886386 0.8043676]
[0.29721716 0.9790907  0.38796583 0.75994223]
[0.00348246 0.7773438  0.00443534 0.02102529]
[0.00338751 0.39687225 0.00446363 0.01271922

 25%|██▌       | 7/28 [00:07<00:21,  1.01s/it]

[0.02343817 0.00658035 0.01959521 0.02343817]
[0.00693341 0.00143376 0.00693341 0.00693341]
[0.001551  0.0007464 0.001551  0.001551 ]
[0.00033534 0.00033534 0.00033534 0.00033534]
[6.756427e-05 6.756427e-05 6.756427e-05 6.756427e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[3.5795570e-06 3.5795672e-06 3.5795672e-06 3.5795672e-06]
[4.843674e-05 4.843669e-05 4.843669e-05 4.843669e-05]
[0.00703243 0.00028492 0.00028492 0.00028492]
[0.05606711 0.00059212 0.00059212 0.00059212]
[0.41202638 0.00135179 0.00135178 0.00135179]
[0.95080507 0.02057225 0.02057226 0.02057226]
[0.98705125 0.02057226 0.02057226 0.02057225]
[0.9324075  0.02057225 0.02057225 0.08215266]
[0.86841416 0.01722653 0.02057225 0.3076588 ]
[0.84961385 0.1463542  0.00400053 0.99899215]
[0.93597955 0.57364696 0.01055571 0.999482  ]
[0.97714144 0.999017   0.02138023 0.9961796 ]
[0.9963631 0.9614403 0.4867739 0.9907418]
[0.99812084 0.8042304  0.9740975  0.9965592 ]
[0.9945576  0.8903956  0.97604126 0.99276793]
[0

 29%|██▊       | 8/28 [00:08<00:19,  1.01it/s]

[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[3.5795606e-06 3.5795672e-06 3.5795672e-06 3.5795638e-06]
[2.3486968e-05 4.8436690e-05 4.8436690e-05 4.8436741e-05]
[0.00012523 0.00028492 0.00028492 0.00028492]
[0.00671654 0.00059212 0.00059212 0.00059212]
[0.19670586 0.00135179 0.00135178 0.00135179]
[0.66337264 0.02057225 0.02057225 0.08215262]
[0.97874534 0.02057225 0.02057225 0.24135256]
[0.9088629  0.00470313 0.02057224 0.72946423]
[0.7380139  0.06789996 0.00274786 0.95080507]
[0.78055847 0.59141064 0.00279127 0.98705125]
[0.8610997  0.89117604 0.00267452 0.93240756]
[0.9543386  0.7592407  0.00604615 0.8159655 ]
[0.99190134 0.87185264 0.4437305  0.8665995 ]
[0.9965643  0.73551106 0.9829983  0.9576419 ]
[0.9988005  0.89189845 0.97182965 0.9940941 ]
[0.99869305 0.9660144  0.15084317 0.99847597]
[0.99380165 0.83761257 0.00167868 0.994402  ]
[0.6659017  0.42108813 0.00203707 0.6426275 ]
[0.22202331 0.00554012 0.00215749 0.23937069]
[0.00130285 0.00273245 0.00532867 0.00188929

 32%|███▏      | 9/28 [00:08<00:18,  1.02it/s]

[0.0008343  0.00076659 0.00693341 0.0008343 ]
[0.00055528 0.00050242 0.001551   0.00055528]
[0.00028276 0.00033534 0.00033534 0.00028276]
[6.756427e-05 6.756427e-05 6.756427e-05 6.756427e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[1.40183705e-08 3.57956719e-06 3.57956719e-06 3.57956378e-06]
[2.2581589e-06 4.8436690e-05 4.8436690e-05 4.8436832e-05]
[5.1983538e-05 2.8492184e-04 2.8492184e-04 2.8492158e-04]
[0.0012002  0.00059212 0.00059212 0.00059212]
[0.04553561 0.00135179 0.00135178 0.00025702]
[0.9974137  0.02057226 0.02057225 0.00704879]
[0.98832893 0.0010787  0.02057226 0.07415757]
[0.88760084 0.00226425 0.0026937  0.49409822]
[0.7630184  0.00357262 0.0021563  0.6633725 ]
[0.05664172 0.01130557 0.0011065  0.97874534]
[8.5915405e-01 1.2377636e-01 5.8665132e-04 8.6898398e-01]
[0.9171108  0.27344924 0.00222171 0.715434  ]
[0.9522718 0.9726778 0.3722918 0.7947662]
[0.97495407 0.9219778  0.9998938  0.9214822 ]
[0.99030113 0.98153126 0.8581548  0.9812376 ]
[0.99706036 

 36%|███▌      | 10/28 [00:09<00:17,  1.02it/s]

[5.1034658e-05 6.7564273e-05 6.7564273e-05 5.1034658e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[1.6735029e-08 3.5795672e-06 3.5795672e-06 3.5795638e-06]
[5.6488225e-06 4.8436690e-05 4.8436690e-05 4.8436690e-05]
[0.00031301 0.00028492 0.00028492 0.00028492]
[3.5836514e-02 5.9211679e-04 5.9211679e-04 8.9529211e-05]
[8.0472445e-01 1.3517849e-03 1.3517863e-03 2.0318660e-04]
[0.80395716 0.0011531  0.02057226 0.00222948]
[0.8996899  0.00384217 0.00516583 0.02310282]
[0.02866267 0.00226377 0.00303627 0.17273967]
[0.20623247 0.00135606 0.00142917 0.9974137 ]
[0.39463386 0.02046128 0.0011992  0.9863483 ]
[0.30330577 0.24527591 0.00364525 0.88231725]
[0.19895501 0.9988249  0.07232425 0.7548412 ]
[0.9436844  0.9959706  0.97721297 0.08982491]
[0.97149235 0.9325833  0.99994457 0.17058693]
[0.98859894 0.99598134 0.7777868  0.3567477 ]
[0.9943816  0.9839171  0.01418426 0.98722863]
[0.99878234 0.5720583  0.0054767  0.9961222 ]
[0.9976548  0.11111844 0.00267736 0.99930036]
[0.97637

 39%|███▉      | 11/28 [00:10<00:16,  1.04it/s]

[0.00047296 0.00038137 0.001551   0.00047296]
[8.268287e-05 3.353367e-04 3.353367e-04 8.268287e-05]
[5.0394152e-05 6.7564273e-05 6.7564273e-05 5.0394152e-05]
[1.4236611e-05 1.1216427e-05 1.1216427e-05 1.4236611e-05]
[4.5376898e-09 3.5795672e-06 3.5795672e-06 3.5795638e-06]
[2.4121925e-07 4.8436690e-05 4.8436690e-05 4.8436785e-05]
[1.0533068e-05 2.8492158e-04 2.8492184e-04 1.7783482e-04]
[0.00047941 0.00059212 0.00059212 0.00015962]
[0.00596257 0.00052705 0.00135179 0.0005585 ]
[0.02391326 0.00507677 0.00192924 0.01558529]
[0.01045875 0.00636406 0.00529799 0.3404944 ]
[0.00280853 0.0044317  0.00250673 0.99973863]
[3.5593060e-03 3.4939926e-02 8.7823608e-04 9.9919373e-01]
[2.4273116e-02 3.6216459e-01 6.0429832e-04 9.5080703e-01]
[0.18668602 0.9673217  0.00312433 0.41580734]
[0.3269226  0.99938285 0.17890061 0.16043465]
[0.23158449 0.99644    0.99983525 0.03119169]
[0.4761252  0.96120465 0.99898785 0.11672161]
[0.5669593  0.9952121  0.46410608 0.19639473]
[0.99840957 0.97519886 0.001228   

 43%|████▎     | 12/28 [00:11<00:15,  1.04it/s]

[0.00046785 0.00239007 0.01048613 0.00049418]
[0.00023202 0.00052861 0.00693341 0.00023202]
[0.00035815 0.00036576 0.001551   0.00035815]
[9.0461275e-05 3.3533669e-04 3.3533669e-04 9.0461275e-05]
[1.9409701e-05 6.7564273e-05 6.7564273e-05 1.9409701e-05]
[1.0126397e-05 1.1216427e-05 1.1216427e-05 1.0126397e-05]
[2.3779592e-09 3.5795672e-06 3.5795672e-06 3.5795638e-06]
[3.5017152e-07 4.8436690e-05 4.8436690e-05 3.9291706e-05]
[2.9517998e-05 2.8492158e-04 2.8492184e-04 2.0525158e-04]
[0.00033068 0.00105995 0.00059212 0.00011174]
[0.00273575 0.00500055 0.00135179 0.00280448]
[0.00691714 0.01150102 0.00160188 0.40354022]
[0.53970903 0.0039894  0.00457047 0.9999254 ]
[0.00814656 0.00315675 0.00235475 0.9996208 ]
[0.00370358 0.02152141 0.00328357 0.9855129 ]
[0.00350167 0.3790667  0.00820647 0.8728473 ]
[0.00402421 0.99951756 0.20984057 0.03036625]
[0.00920204 0.9994789  0.9935409  0.00195787]
[0.02621641 0.9798384  0.99993956 0.00530666]
[0.0850179 0.9341352 0.9414226 0.0084143]
[0.4576062  

 46%|████▋     | 13/28 [00:12<00:14,  1.04it/s]

[7.293637e-05 3.353367e-04 3.353367e-04 1.308535e-04]
[2.1504873e-05 6.7564273e-05 6.7564273e-05 2.7181857e-05]
[1.1376393e-05 1.1216427e-05 1.1216427e-05 2.1779575e-05]
[6.6909895e-09 3.5795672e-06 3.5795672e-06 2.0797406e-06]
[2.4899484e-07 4.8436741e-05 4.8436690e-05 1.9792273e-05]
[0.00012701 0.00016389 0.00028492 0.00017159]
[0.00336144 0.00108649 0.00059212 0.00146709]
[0.24976853 0.00448729 0.00135179 0.17730254]
[0.86820364 0.00323954 0.00170209 0.97544587]
[0.7440295  0.00541289 0.00232653 0.9998161 ]
[0.4910265  0.01101037 0.00495579 0.99344563]
[0.4275801  0.3001916  0.00670867 0.6169054 ]
[0.58883005 0.9997987  0.04235207 0.06302118]
[0.7466701  0.99958044 0.40722796 0.52324957]
[0.84970075 0.9947278  0.95727146 0.01797574]
[0.947413   0.97902244 0.9997589  0.00587092]
[0.9886982  0.9629163  0.6418696  0.00119832]
[9.9723130e-01 9.9596149e-01 4.2624565e-04 2.4953862e-03]
[0.99982065 0.9812666  0.00248709 0.01153004]
[0.99910283 0.63427854 0.00195383 0.10556892]
[0.99849427 

 50%|█████     | 14/28 [00:13<00:13,  1.03it/s]

[1.0542363e-05 1.1216427e-05 1.1216427e-05 1.3220075e-05]
[1.1696885e-07 3.5795638e-06 3.5795672e-06 1.6670571e-06]
[2.9502954e-07 4.8436741e-05 4.8436690e-05 2.2029624e-06]
[1.3197917e-05 2.5741008e-04 2.8492184e-04 2.9129158e-05]
[0.002576   0.00173425 0.00059212 0.00130187]
[0.0256706  0.00241254 0.00135179 0.32441008]
[0.8335231  0.00951669 0.00151405 0.875064  ]
[0.9997211  0.02073729 0.00122668 0.9995085 ]
[0.9998048  0.33123985 0.00213483 0.999332  ]
[0.99871635 0.95920646 0.0026739  0.9449561 ]
[0.99926    0.9998305  0.00286909 0.81589776]
[0.99968755 0.9981548  0.650047   0.63214594]
[0.99996233 0.99089557 0.9998362  0.73567086]
[0.99995565 0.9457203  0.97315615 0.5362714 ]
[0.99985325 0.9812013  0.01705264 0.7455394 ]
[0.9997662  0.997235   0.00833834 0.8101406 ]
[0.9990934  0.96771944 0.00487599 0.85857385]
[0.9917265  0.54185706 0.00373452 0.2526707 ]
[0.9357554  0.09438003 0.00449664 0.97985566]
[4.1409978e-03 8.4445527e-04 5.6048278e-03 9.9957842e-01]
[1.1090169e-03 1.914

 54%|█████▎    | 15/28 [00:14<00:12,  1.03it/s]

[0.00056138 0.00056251 0.00693341 0.00029919]
[0.00020609 0.00037374 0.001551   0.0002226 ]
[3.6517104e-05 3.3533669e-04 3.3533669e-04 5.6492325e-05]
[1.6456110e-05 6.7564273e-05 6.7564273e-05 2.3844723e-05]
[9.5765017e-06 1.1216427e-05 1.1216427e-05 1.0266382e-05]
[1.4159522e-07 3.5795638e-06 3.5795672e-06 4.4012771e-09]
[2.2550062e-06 4.8436832e-05 4.8436690e-05 2.1882374e-07]
[3.0275256e-05 3.2705098e-04 2.8492184e-04 1.2395470e-06]
[1.7088604e-03 1.7289865e-04 5.9211708e-04 5.7716890e-05]
[0.01196722 0.00086858 0.00085702 0.13989198]
[0.4378486  0.00449357 0.00121867 0.60119176]
[0.7476511  0.01569157 0.00159228 0.99876475]
[0.9995634  0.3884746  0.00497471 0.99296486]
[0.9995945  0.9093423  0.00234433 0.99416417]
[0.99907863 0.9995454  0.16348402 0.99836236]
[0.99887425 0.99804425 0.9565078  0.9997327 ]
[0.997614   0.9842718  0.99991083 0.9993387 ]
[0.99749446 0.9749825  0.72333944 0.99515224]
[0.99901533 0.9919069  0.04916794 0.9997255 ]
[0.9776112  0.9950641  0.00619914 0.999279

 57%|█████▋    | 16/28 [00:15<00:11,  1.03it/s]

[1.0679772e-05 6.7564273e-05 6.7564273e-05 1.3872691e-05]
[7.0266847e-06 1.1216427e-05 1.1216427e-05 9.6195126e-06]
[9.4252528e-08 3.5795638e-06 3.5795672e-06 1.6954060e-10]
[6.0706606e-07 4.8436785e-05 4.8436690e-05 7.7864350e-08]
[7.7038421e-06 1.6388920e-04 2.8492184e-04 8.6130927e-07]
[1.4049218e-05 1.6539560e-05 5.9211737e-04 4.3141194e-05]
[0.00067813 0.0005337  0.00054276 0.01996476]
[0.00974675 0.00066086 0.00094539 0.30872124]
[3.8530413e-02 6.9655073e-03 8.1476645e-04 9.9754071e-01]
[1.8194553e-01 3.5761565e-01 6.5131602e-04 9.7419840e-01]
[0.3409426  0.8161165  0.00191411 0.9806348 ]
[0.21189427 0.9996207  0.30408236 0.9926408 ]
[0.11227726 0.9986002  0.9118043  0.99411064]
[0.00614724 0.9839385  0.9998084  0.9943363 ]
[0.00205901 0.98978186 0.5863861  0.99423295]
[7.0646923e-04 9.9165863e-01 4.3606557e-02 9.9795216e-01]
[3.1164174e-05 9.8962420e-01 9.4817439e-03 9.9788326e-01]
[2.7142871e-05 9.3272978e-01 1.0951543e-02 9.9801683e-01]
[2.4960304e-06 6.0168880e-01 9.9442089e-

 61%|██████    | 17/28 [00:16<00:11,  1.04s/it]

[1.7986944e-04 3.9219731e-04 6.9334065e-03 9.7737582e-05]
[0.00050203 0.00032102 0.001551   0.00016824]
[5.2825384e-05 3.3533669e-04 3.3533669e-04 5.7673642e-05]
[8.4483499e-06 6.7564273e-05 6.7564273e-05 1.0250747e-05]
[4.6060049e-06 1.1216427e-05 1.1216427e-05 6.4778160e-06]
[7.1686451e-08 3.5795638e-06 3.5795672e-06 5.5293503e-10]
[2.1494513e-06 4.8436741e-05 4.8436690e-05 1.5410717e-07]
[1.7856170e-05 6.8637477e-05 2.8492184e-04 1.8582808e-06]
[4.03411696e-06 6.25714383e-05 6.16389443e-04 1.19174736e-04]
[2.2491542e-05 3.0718025e-04 7.9423038e-04 1.6891150e-02]
[1.3743716e-04 8.1220712e-04 1.3560588e-03 2.3954885e-01]
[3.8227005e-04 5.7172645e-03 5.0733716e-04 4.8249978e-01]
[4.9212022e-04 1.2340439e-01 1.9284360e-04 4.4778341e-01]
[2.0266033e-04 9.9909735e-01 1.7316360e-03 9.7179055e-01]
[6.2645166e-05 9.9925548e-01 1.8583855e-01 9.6862954e-01]
[5.2937488e-05 9.9710000e-01 8.4989721e-01 9.6889335e-01]
[5.7518650e-05 9.8530662e-01 9.9983525e-01 3.6096895e-01]
[5.9890444e-05 9.88910

 64%|██████▍   | 18/28 [00:18<00:10,  1.09s/it]

[2.3646789e-04 1.4938945e-03 2.8130233e-03 1.9975714e-05]
[2.3738209e-04 5.0814607e-04 6.9334065e-03 5.1232826e-05]
[0.00062688 0.00032165 0.001551   0.00016035]
[9.7383963e-05 3.3533669e-04 3.3533669e-04 3.3046996e-05]
[7.7043933e-06 6.7564273e-05 6.7564273e-05 6.5145414e-06]
[2.4416329e-06 1.1216427e-05 1.1216427e-05 5.0843819e-06]
[4.5187213e-07 3.5795672e-06 3.5795672e-06 2.5859810e-09]
[1.1524730e-06 1.5681637e-05 4.8436690e-05 2.2325119e-07]
[7.2743201e-06 5.7334590e-05 2.8492184e-04 4.6374043e-06]
[1.0039233e-05 4.8587601e-05 6.1436626e-04 2.2267302e-05]
[3.5717683e-05 4.0561866e-04 7.2749000e-04 1.8093715e-04]
[0.00240862 0.00574816 0.00095874 0.00341297]
[0.00293071 0.19411027 0.00036076 0.00534261]
[2.0593985e-04 8.7079966e-01 2.8620337e-04 2.1965664e-02]
[3.4679997e-05 9.9979812e-01 1.6278869e-03 1.8942475e-02]
[6.8099871e-05 9.9939406e-01 8.6998604e-02 7.5874818e-03]
[4.1684878e-04 9.9523133e-01 8.1393278e-01 1.9989612e-03]
[8.3840947e-05 9.9283361e-01 9.9987066e-01 3.97187

 68%|██████▊   | 19/28 [00:19<00:09,  1.06s/it]

[2.7714254e-04 3.2502657e-04 1.5510027e-03 7.0377384e-05]
[4.5040902e-05 3.3533669e-04 3.3533669e-04 2.7743554e-05]
[5.9618274e-06 6.7564273e-05 6.7564273e-05 3.2526484e-06]
[1.6853555e-06 1.1216427e-05 1.1216427e-05 4.8065035e-06]
[1.6264748e-07 2.0797445e-06 3.5795672e-06 9.2319548e-09]
[3.7827554e-06 1.0110263e-05 4.8436690e-05 1.8942872e-07]
[7.6880115e-06 1.3867148e-05 2.8492158e-04 2.7663123e-06]
[9.5555470e-06 5.2933898e-05 3.2835754e-04 4.8834286e-06]
[0.00034277 0.00024033 0.00056959 0.00013159]
[0.01080253 0.00741777 0.00059539 0.00590328]
[0.0012455  0.2777161  0.00041901 0.00344849]
[8.5605477e-04 7.4929065e-01 6.8605272e-04 4.4065472e-03]
[6.4701709e-04 9.9967992e-01 1.7327465e-03 5.5513224e-03]
[2.8375673e-04 9.9836332e-01 8.6590417e-02 5.5726939e-03]
[1.6841394e-04 9.8941457e-01 7.7274418e-01 7.3653273e-04]
[3.4332945e-04 9.9109674e-01 7.0832169e-01 3.2615580e-04]
[4.899122e-05 9.943527e-01 9.303308e-01 9.981984e-05]
[5.4570275e-05 8.0208087e-01 5.2142882e-01 1.0018871e-

 71%|███████▏  | 20/28 [00:20<00:08,  1.04s/it]

[5.294503e-06 6.756427e-05 6.756427e-05 6.162713e-06]
[2.9596308e-06 1.1216427e-05 1.1216427e-05 2.6056837e-06]
[3.0447899e-07 1.6670571e-06 3.5795672e-06 3.2994063e-08]
[4.1138992e-07 3.5773660e-06 4.8436690e-05 2.4605009e-07]
[8.2228635e-06 1.0579234e-05 1.6388889e-04 4.1462940e-06]
[1.4121162e-05 8.7460703e-06 2.4086371e-04 2.0562935e-05]
[0.00019966 0.00013371 0.00063066 0.00013314]
[0.00596718 0.0027254  0.00068676 0.01088051]
[0.00271212 0.17784439 0.00040376 0.00712703]
[2.9742913e-03 7.2818899e-01 3.3329750e-04 7.3002856e-03]
[5.6734623e-04 9.9976689e-01 1.9753202e-04 7.0315008e-03]
[2.5742015e-04 9.9827588e-01 3.1589586e-04 3.5745255e-03]
[4.5290953e-04 9.9518102e-01 1.6185209e-02 9.2779193e-04]
[4.3171545e-04 9.7362876e-01 7.2955298e-01 2.0651873e-04]
[3.8741223e-04 8.7687939e-01 6.6654481e-02 7.9847567e-05]
[1.0017313e-04 2.8404540e-01 2.5105081e-03 1.8423396e-05]
[4.3825345e-05 1.6714356e-04 5.8288308e-04 1.3042066e-06]
[3.1524542e-05 5.2967033e-04 3.3372486e-04 8.8523296e-

 75%|███████▌  | 21/28 [00:21<00:07,  1.03s/it]

[1.9383353e-04 2.0846524e-03 2.0572260e-02 1.7844135e-05]
[5.4665910e-05 7.6535903e-04 6.9334065e-03 5.9528647e-05]
[0.00045129 0.00037464 0.001551   0.00010542]
[6.467850e-05 3.353367e-04 3.353367e-04 5.821216e-05]
[2.1070404e-05 6.7564273e-05 6.7564273e-05 6.1859005e-06]
[8.7789949e-06 1.1216427e-05 1.1216427e-05 1.7041832e-06]
[1.6785559e-06 1.5705856e-06 3.5795672e-06 1.7521366e-07]
[4.3588079e-06 7.2241522e-07 4.8436690e-05 1.4824442e-06]
[5.4461001e-05 4.2199185e-06 1.6240592e-04 7.5534185e-06]
[3.0990501e-04 6.6641196e-06 4.2075847e-04 1.5575577e-05]
[4.8287783e-04 3.6094709e-05 5.3613307e-04 2.5256377e-04]
[0.01135273 0.00246905 0.00057625 0.00801564]
[0.00301246 0.09358873 0.00052805 0.00945564]
[3.1726859e-03 6.9637543e-01 1.5692115e-04 1.2686673e-02]
[2.3494354e-03 9.9970859e-01 1.5708208e-04 5.8261980e-03]
[4.1505040e-04 9.9860913e-01 2.0861739e-04 4.2719161e-03]
[1.6504388e-04 9.8737806e-01 1.5500898e-04 1.2494131e-03]
[5.2326668e-05 8.5983157e-01 1.5083885e-04 2.7456169e-

 79%|███████▊  | 22/28 [00:22<00:06,  1.02s/it]

[1.3616716e-04 3.3533669e-04 3.3533669e-04 5.5545152e-05]
[3.8351038e-05 6.7564273e-05 6.7564273e-05 1.2205589e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.7674874e-06]
[9.0548008e-07 6.0266757e-07 3.5795672e-06 4.7938369e-07]
[1.4881151e-05 2.8990178e-07 4.8436690e-05 2.0590953e-06]
[1.1089611e-04 4.6555679e-06 1.9616507e-04 1.9200579e-05]
[1.2990825e-04 9.7919483e-06 2.1785183e-04 4.8878850e-05]
[3.0540075e-04 2.8480652e-05 3.6640296e-04 4.2599297e-04]
[0.00356502 0.00431443 0.00099942 0.01040426]
[0.00175783 0.04874762 0.00098342 0.01004445]
[1.2558086e-03 5.8010238e-01 3.4333041e-04 1.7716836e-02]
[1.1907707e-03 9.9960297e-01 1.5207521e-04 5.1584239e-03]
[2.7729900e-04 9.9607003e-01 5.9693328e-05 1.9793541e-03]
[1.6701181e-04 9.5136213e-01 5.6281493e-05 3.9019281e-04]
[2.0944330e-04 5.6930810e-01 4.1640081e-04 7.9574755e-05]
[1.8855999e-04 4.3582719e-02 4.4592409e-05 3.2536482e-04]
[1.3080235e-04 2.5633238e-03 8.1662489e-05 8.2063496e-05]
[9.1844537e-05 1.0235714e-03 7.1800532

 82%|████████▏ | 23/28 [00:23<00:05,  1.01s/it]

[1.1216427e-05 1.1216427e-05 1.1216427e-05 4.5909314e-07]
[1.9541847e-06 1.7174035e-07 3.5795672e-06 1.1895487e-06]
[3.4049635e-06 4.8069620e-07 4.8436690e-05 2.6874741e-06]
[3.9916446e-05 1.5558446e-05 1.9616488e-04 1.0862612e-05]
[1.7351964e-04 1.8391500e-05 2.1785224e-04 6.4748667e-05]
[6.0806173e-04 2.1724914e-05 1.7016343e-03 2.1948977e-04]
[0.00532628 0.0062186  0.00188703 0.00440021]
[0.00357175 0.04796139 0.00116672 0.01498037]
[0.0018663  0.5395991  0.00059165 0.01032698]
[2.1564818e-03 9.9974507e-01 1.3104492e-04 4.5193313e-03]
[1.6283264e-03 9.9769163e-01 5.0515454e-04 6.4164994e-04]
[1.2869800e-03 9.8374987e-01 4.1842854e-04 4.8382807e-04]
[9.98828211e-04 7.96076238e-01 1.20772806e-04 2.55176186e-04]
[9.3743793e-04 3.0574289e-01 2.3186188e-04 2.0829975e-04]
[8.5122237e-04 2.2862400e-03 2.7177605e-04 6.2466323e-05]
[5.9718965e-04 1.6154099e-03 2.5687879e-04 3.6433445e-05]
[5.2728917e-04 7.8371573e-05 2.3395126e-04 3.1358431e-05]
[4.3107232e-04 1.4682415e-04 3.0422874e-04 2.6

 86%|████████▌ | 24/28 [00:24<00:03,  1.01it/s]

[6.9334065e-03 5.0193921e-04 6.9334065e-03 5.9032198e-05]
[1.5510027e-03 3.5334274e-04 1.5510027e-03 2.6526692e-05]
[3.353367e-04 3.353367e-04 3.353367e-04 7.705075e-05]
[6.7564273e-05 6.7564273e-05 6.7564273e-05 6.2088793e-06]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.8661160e-06]
[3.5795672e-06 3.1453720e-07 3.5795672e-06 1.6057086e-06]
[4.8436690e-05 1.3849419e-06 4.8436690e-05 3.3633792e-06]
[2.8492184e-04 1.8808574e-05 1.9616526e-04 5.2886677e-05]
[5.9211679e-04 7.7912628e-05 1.0092229e-03 1.6061854e-04]
[1.3517849e-03 4.5849654e-05 2.9215598e-03 4.8222535e-04]
[0.02057226 0.00916007 0.01394073 0.00481834]
[0.02057226 0.05839135 0.0027647  0.02278656]
[0.02057226 0.651723   0.00219271 0.00256961]
[0.02057226 0.9997303  0.00187624 0.00622843]
[0.02057226 0.9980458  0.00439129 0.0030682 ]
[0.02057226 0.99398094 0.00410623 0.00099879]
[2.057226e-02 9.018390e-01 3.522421e-04 2.705323e-04]
[2.0572260e-02 3.0492339e-01 8.0507575e-04 1.4646689e-04]
[0.02057226 0.00097896 0.00100092 0.

 89%|████████▉ | 25/28 [00:24<00:02,  1.02it/s]

[6.756427e-05 6.756427e-05 6.756427e-05 3.337527e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 8.7789949e-06]
[3.5795672e-06 4.3520032e-07 3.5795672e-06 7.9229193e-07]
[4.8436690e-05 1.1656412e-06 4.8436690e-05 4.8760203e-06]
[2.8492184e-04 8.2247852e-06 3.4489986e-04 3.4114295e-05]
[5.9211679e-04 6.2816260e-05 6.7064993e-04 2.6057867e-04]
[1.3517849e-03 2.3973525e-05 2.7514137e-03 8.4472081e-04]
[0.02057226 0.0055318  0.01644575 0.01532892]
[0.02057226 0.04912039 0.00935723 0.0144879 ]
[0.02057226 0.6182312  0.00483943 0.87002355]
[0.02057226 0.99959964 0.00413419 0.82958305]
[0.02057226 0.9990319  0.01031733 0.03703569]
[0.02057226 0.9969638  0.00676808 0.02044362]
[0.02057226 0.87979233 0.00180491 0.01181328]
[0.02057226 0.31952205 0.00230159 0.0056421 ]
[0.02057226 0.00053741 0.00272014 0.00255416]
[0.02057226 0.00067507 0.00164593 0.00447903]
[0.02057226 0.00021031 0.00298619 0.00124715]
[0.02057226 0.00021574 0.00099866 0.00119556]
[0.02057226 0.00103575 0.00061472 0.00078306]


 93%|█████████▎| 26/28 [00:25<00:01,  1.01it/s]

[0.00693341 0.00063893 0.00693341 0.00019656]
[0.001551  0.001551  0.001551  0.0002829]
[0.00033534 0.00033534 0.00033534 0.00020894]
[6.756427e-05 6.756427e-05 6.756427e-05 6.756427e-05]
[1.1216427e-05 1.1216427e-05 1.1216427e-05 1.1216427e-05]
[3.5795672e-06 4.3520117e-07 3.5795672e-06 3.5795606e-06]
[4.8436690e-05 1.1656412e-06 4.8436690e-05 4.8436785e-05]
[2.8492184e-04 8.2247689e-06 3.2705069e-04 2.8492158e-04]
[5.9211679e-04 6.2816260e-05 6.2015274e-04 1.3055902e-02]
[1.3517849e-03 2.3973525e-05 3.7162495e-03 1.1225772e-01]
[0.02057226 0.00393649 0.01144963 0.5492337 ]
[0.02057226 0.06019994 0.01015718 0.97882825]
[0.02057226 0.5958819  0.01069267 0.9886386 ]
[0.02057226 0.9998122  0.00844428 0.38796598]
[0.02057226 0.999503   0.00761438 0.00443534]
[0.02057226 0.99818194 0.00491395 0.00446362]
[0.02057226 0.8085781  0.00484886 0.00641202]
[0.02057226 0.31542283 0.00396817 0.01366487]
[0.02057226 0.13993827 0.00225599 0.02204752]
[0.02057226 0.60181874 0.00160335 0.02996018]
[0.0

 96%|█████████▋| 27/28 [00:27<00:01,  1.00s/it]

[0.001551   0.001551   0.8183025  0.00170328]
[3.3533669e-04 3.3533669e-04 3.8472760e-01 3.8205838e-04]
[6.7564273e-05 6.7564273e-05 2.0196147e-01 5.1034709e-05]
[1.1216427e-05 1.1216427e-05 5.6224518e-02 1.1216427e-05]
[3.5795672e-06 4.3520032e-07 3.5795672e-06 3.5795638e-06]
[4.8436690e-05 1.1656412e-06 4.8436690e-05 4.8436832e-05]
[2.8492184e-04 8.2247852e-06 2.8492184e-04 8.7498745e-05]
[5.9211679e-04 6.2816260e-05 9.0983848e-04 3.1804014e-04]
[1.3517849e-03 2.1003716e-05 1.8940388e-03 1.5853620e-03]
[0.02057226 0.00310324 0.0080223  0.4867739 ]
[0.02057226 0.05564062 0.01069513 0.9740975 ]
[0.02057226 0.6577685  0.01159313 0.97604126]
[0.02057226 0.9998379  0.00715889 0.19957528]
[0.02057226 0.99931395 0.00897493 0.00207641]
[0.02057226 0.9987871  0.00748175 0.00252826]
[0.02057226 0.99850035 0.00963451 0.00396231]
[0.02057226 0.99728906 0.00525892 0.00844421]
[0.02057226 0.9679179  0.00513797 0.01421759]
[0.02057226 0.6922874  0.0039757  0.02335427]
[0.02057226 0.33808136 0.00518

100%|██████████| 28/28 [00:28<00:00,  1.01s/it]

[0.02454364 0.01287531 0.9973212  0.7018476 ]
[0.00409542 0.00249778 0.9985014  0.48433676]
[1.8399636e-03 9.6208876e-04 9.8346901e-01 3.3574796e-03]
[2.5902016e-04 2.7095355e-04 8.9240301e-01 3.5131534e-04]
[9.208640e-05 9.918810e-05 6.393941e-01 3.311634e-05]
[1.4236598e-05 2.4702143e-05 2.6195969e-02 6.6095486e-06]


In [31]:
arr.shape


(4, 28, 28, 1)

In [6]:
mask = np.zeros((12,12))

In [8]:
mask.shape

(12, 12)

In [10]:

# importing numpy
import numpy as np
  
array = np.zeros((10,10, 2))
array[: array.shape[0] // 2, ] = 1.0

In [11]:
array.shape

(10, 10, 2)

In [ ]:
mask[: mask.shape[0] // 2] = 1.0

In [ ]:
mask

In [ ]:
filter_size = mask.shape[0]
filter_center = filter_size / 2

# Zero out all weights below the center.
mask[math.ceil(filter_center):] = 0

In [ ]:
mask